# Generated by Django 4.2.27 on 2026-01-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fee_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='fee_total',
            field=models.IntegerField(default=0),
        ),
    ]
