# Generated by Django 4.2.27 on 2026-01-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_scholarship_alter_classroom_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='house_team',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Any allergies or conditions', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='preferred_stream',
            field=models.CharField(choices=[('General', 'General'), ('Science (PCM)', 'Science (PCM)'), ('Science (PCB)', 'Science (PCB)'), ('Commerce', 'Commerce'), ('Arts', 'Arts')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='route_name',
            field=models.CharField(blank=True, help_text='If School Bus', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='transport_mode',
            field=models.CharField(choices=[('School Bus', 'School Bus'), ('Private', 'Private'), ('Self', 'Self')], default='Self', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
    ]
