# Generated by Django 4.2.27 on 2026-01-20 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_book_librarytransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('designation', models.CharField(choices=[('Teacher', 'Teacher'), ('Principal', 'Principal'), ('Accountant', 'Accountant'), ('Driver', 'Driver'), ('Cleaner', 'Cleaner'), ('Other', 'Other')], max_length=100)),
                ('salary', models.IntegerField(default=0, help_text='Monthly Salary')),
                ('join_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.school')),
            ],
        ),
    ]
