# Generated by Django 4.2.27 on 2026-01-21 07:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Cheque', 'Cheque')], default='Cash', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.school')),
            ],
        ),
        migrations.RemoveField(
            model_name='parent',
            name='school',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='school',
        ),
        migrations.RemoveField(
            model_name='studentdocument',
            name='school',
        ),
        migrations.RemoveField(
            model_name='studentdocument',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studenthostel',
            name='room',
        ),
        migrations.RemoveField(
            model_name='studenthostel',
            name='school',
        ),
        migrations.RemoveField(
            model_name='studenthostel',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentscholarship',
            name='scholarship',
        ),
        migrations.RemoveField(
            model_name='studentscholarship',
            name='school',
        ),
        migrations.RemoveField(
            model_name='studentscholarship',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='examscore',
            name='school',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='school',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='school',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='school',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='school',
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.school'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='examscore',
            name='exam_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='librarytransaction',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='librarytransaction',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.school'),
        ),
        migrations.AlterField(
            model_name='librarytransaction',
            name='status',
            field=models.CharField(default='Issued', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='fee_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='fee_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='house_team',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='medical_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='preferred_stream',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='route_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='transport_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.school'),
        ),
        migrations.AlterField(
            model_name='studenttransport',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='studenttransport',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.school'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='video_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='transportroute',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.school'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='Staff', max_length=20),
        ),
        migrations.DeleteModel(
            name='HostelRoom',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Scholarship',
        ),
        migrations.DeleteModel(
            name='StudentDocument',
        ),
        migrations.DeleteModel(
            name='StudentHostel',
        ),
        migrations.DeleteModel(
            name='StudentScholarship',
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.classroom'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.school'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='school',
        ),
    ]
