# Generated by Django 4.2.27 on 2026-01-21 09:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_feestructure_feetransaction_remove_parent_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('month_year', models.CharField(max_length=50)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque')], default='Bank Transfer', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.staff')),
            ],
        ),
    ]
