# Generated by Django 4.2.27 on 2026-01-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_salarytransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feetransaction',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='feetransaction',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='feetransaction',
            name='school',
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='month_year',
            field=models.CharField(default='January 2026', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feetransaction',
            name='status',
            field=models.CharField(default='Paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='feetransaction',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feetransaction',
            name='payment_mode',
            field=models.CharField(max_length=50),
        ),
    ]
