# Generated by Django 4.2.27 on 2026-01-23 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_remove_feetransaction_receipt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttransport',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studenttransport',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.transportroute'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studenttransport',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transportroute',
            name='driver_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='transportroute',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.school'),
            preserve_default=False,
        ),
    ]
