# Generated by Django 4.2.27 on 2026-01-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_alter_studenttransport_pickup_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscore',
            name='generated_report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
