# Generated by Django 4.2.27 on 2026-01-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_school_for_unscoped_rows(apps, schema_editor):
    School = apps.get_model('members', 'School')
    Notice = apps.get_model('members', 'Notice')
    Expense = apps.get_model('members', 'Expense')
    StudyMaterial = apps.get_model('members', 'StudyMaterial')

    default_school = School.objects.order_by('id').first()
    if not default_school:
        return

    Notice.objects.filter(school__isnull=True).update(school=default_school)
    Expense.objects.filter(school__isnull=True).update(school=default_school)
    StudyMaterial.objects.filter(school__isnull=True).update(school=default_school)


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_examscore_generated_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.school'),
        ),
        migrations.AddField(
            model_name='expense',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.school'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.school'),
        ),
        migrations.RunPython(backfill_school_for_unscoped_rows, migrations.RunPython.noop),
        migrations.CreateModel(
            name='TransportZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.school')),
            ],
            options={
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TransportStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('stop_code', models.CharField(max_length=50)),
                ('monthly_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.school')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='members.transportzone')),
            ],
            options={
                'unique_together': {('school', 'stop_code')},
            },
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='billing_mode',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Hybrid', 'Hybrid')], default='Manual', max_length=20),
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.transportstop'),
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.transportzone'),
        ),
        migrations.CreateModel(
            name='LateFeePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_days', models.PositiveIntegerField(default=0)),
                ('per_day_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cap_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.school')),
            ],
        ),
        migrations.CreateModel(
            name='FeeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('discount_type', models.CharField(choices=[('Percent', 'Percent'), ('Fixed', 'Fixed')], default='Fixed', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_concession', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.school')),
            ],
            options={
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('due_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Due', 'Due'), ('Partial', 'Partial'), ('Paid', 'Paid'), ('Waived', 'Waived')], default='Due', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'unique_together': {('school', 'student', 'academic_year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='FeePaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Bank', 'Bank'), ('Cheque', 'Cheque'), ('Gateway', 'Gateway')], max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Success', max_length=20)),
                ('upi_ref', models.CharField(blank=True, max_length=120)),
                ('bank_ref', models.CharField(blank=True, max_length=120)),
                ('cheque_no', models.CharField(blank=True, max_length=60)),
                ('gateway_order_id', models.CharField(blank=True, max_length=120)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('legacy_fee_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.feetransaction')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='StudentConcession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.feediscount')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'unique_together': {('school', 'student', 'discount')},
            },
        ),
        migrations.CreateModel(
            name='FeeRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Processed', 'Processed'), ('Rejected', 'Rejected')], default='Initiated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='members.feepaymentreceipt')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.school')),
            ],
        ),
        migrations.CreateModel(
            name='FeePaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='members.feeinstallment')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='members.feepaymentreceipt')),
            ],
        ),
    ]

