# Generated by Django 4.2.27 on 2026-01-31 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_userprofile_role_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AddField(
            model_name='examscore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studenttransport',
            name='billing_mode',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Zone', 'Zone'), ('Stop', 'Stop'), ('Hybrid', 'Hybrid')], default='Manual', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
