# Generated by Django 4.2.27 on 2026-02-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_alter_attendance_options_examscore_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhaar number', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='caste_category',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS')], default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='emergency_relationship',
            field=models.CharField(blank=True, help_text='Relationship with student', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='mother_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='nationality',
            field=models.CharField(blank=True, default='Indian', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='previous_class',
            field=models.CharField(blank=True, help_text='Last class attended', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='previous_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='tc_number',
            field=models.CharField(blank=True, help_text='Transfer Certificate number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
