# Generated by Django 4.2.27 on 2026-02-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_member_aadhaar_number_member_caste_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='member',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual family income', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/birth_certificates/'),
        ),
        migrations.AddField(
            model_name='member',
            name='chronic_conditions',
            field=models.TextField(blank=True, help_text='Diabetes, Asthma, etc.', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='family_doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='family_doctor_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='guardian_relationship',
            field=models.CharField(blank=True, help_text='Grandparent, Uncle, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='known_allergies',
            field=models.TextField(blank=True, help_text='Food, medicine, or other allergies', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='parent_education',
            field=models.CharField(blank=True, help_text='Highest education of parents', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='permanent_address',
            field=models.TextField(blank=True, help_text='If different from current address', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='photo_id',
            field=models.FileField(blank=True, null=True, upload_to='documents/photo_ids/'),
        ),
        migrations.AddField(
            model_name='member',
            name='previous_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='documents/marksheets/'),
        ),
        migrations.AddField(
            model_name='member',
            name='sibling_details',
            field=models.TextField(blank=True, help_text='Name, Class, Admission No of siblings', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sibling_in_school',
            field=models.BooleanField(default=False, help_text='Does student have siblings in this school?'),
        ),
        migrations.AddField(
            model_name='member',
            name='special_needs',
            field=models.TextField(blank=True, help_text='Physical or learning disabilities', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='transfer_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/tc/'),
        ),
        migrations.AddField(
            model_name='member',
            name='vaccination_status',
            field=models.CharField(blank=True, help_text='COVID-19, MMR, etc.', max_length=100, null=True),
        ),
    ]
