# Generated by Django 4.2.27 on 2026-02-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_member_aadhaar_card_member_alternate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='communication_consent',
            field=models.BooleanField(default=True, help_text='Consent for SMS/Email notifications'),
        ),
        migrations.AddField(
            model_name='member',
            name='photo_permission',
            field=models.BooleanField(default=False, help_text='Permission to use photos/videos'),
        ),
        migrations.AddField(
            model_name='member',
            name='terms_consent',
            field=models.BooleanField(default=False, help_text='Agreement to school terms and conditions'),
        ),
    ]
