# Generated by Django 4.2.27 on 2026-02-07 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_member_communication_consent_member_photo_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Linked student when role=STUDENT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='members.member'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='video_link',
            field=models.URLField(blank=True, help_text='YouTube or other video URL', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('OWNER', 'OWNER'), ('ADMIN', 'ADMIN'), ('ACCOUNTANT', 'ACCOUNTANT'), ('TEACHER', 'TEACHER'), ('STAFF', 'STAFF'), ('STUDENT', 'STUDENT')], default='OWNER', max_length=20),
        ),
    ]
