# Generated by Django 4.2.27 on 2026-02-16 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0035_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['-created_at'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True, help_text='School is active and can be accessed'),
        ),
        migrations.AddField(
            model_name='school',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Demo school with sample data'),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='schools/logos/'),
        ),
        migrations.AddField(
            model_name='school',
            name='primary_color',
            field=models.CharField(default='#4e73df', help_text='Hex color code for branding', max_length=7),
        ),
        migrations.AddField(
            model_name='school',
            name='secondary_color',
            field=models.CharField(blank=True, default='#858796', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='super_admin',
            field=models.ForeignKey(blank=True, help_text='Super admin who owns this school', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_schools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
