# Generated by Django 4.2.27 on 2026-02-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_add_school_branding_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('school', 'name', 'section')},
        ),
    ]
